services:
  ember_engine:
    container_name: ember-engine-${ENVIRONMENT}
    restart: always
    build: .
    environment:
      PORT: 80
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME_FILE: /run/secrets/db_name
      DB_PORT: 5432
      DB_HOST: database
      SECRET_SALT_FILE: /run/secrets/secret_salt
      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_TOKEN_FILE: /run/secrets/telegram_token
      ARBITRUM_RPC_URL:
      IS_TESTNET:
      FUNDING_WALLET_ID_FILE: /run/secrets/funding_wallet_id
      EMBER_CORE_URL: http://ember-core
      FF_EMBER_WALLET:
      SQUID_INTEGRATOR_ID:
      FRONTEND_URL:
    secrets:
      - squid_integrator_id
      - db_name
      - db_user
      - db_password
      - funding_wallet_id
      - secret_salt
      - telegram_token
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - shared_network

secrets:
  db_name:
    environment: "DB_NAME"
  db_user:
    environment: "DB_USER"
  db_password:
    environment: "DB_PASSWORD"
  funding_wallet_id:
    environment: "FUNDING_WALLET_ID"
  secret_salt:
    environment: "SECRET_SALT"
  telegram_token:
    environment: "TELEGRAM_BOT_TOKEN"
  squid_integrator_id:
    environment: "SQUID_INTEGRATOR_ID"

networks:
  shared_network:
    name: ember-main-${ENVIRONMENT}
    external: true
