services:
  firepot_chatgpt_app:
    restart: always
    build: .
    environment:
      PORT: 3001
      CHROMA_PORT: 8000
      DB_URI: ${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
      OPENAI_API_KEY:
      SECRET_SALT:
      TELEGRAM_BOT_TOKEN:
      ARBITRUM_RPC_URL:
      TELEGRAM_BOT_USERNAME:
      IS_TESTNET:
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - shared_network
    depends_on:
      - database
      - chroma_server

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  chroma_server:
    image: chromadb/chroma:latest
    restart: always
    volumes:
      - type: bind
        source: ./chroma
        target: /chroma
      - type: volume
        source: index_data
        target: /index_data
    networks:
      - shared_network

volumes:
  index_data:
    driver: local

networks:
  shared_network:
    external: true
