services:
  telegram_bot:
    restart: always
    build: .
    environment:
      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_TOKEN_FILE: /run/secrets/telegram_token
      EMBER_API_URL: http://ember-api/v1/public/telegram
      FF_EMBER_WALLET:
    secrets:
      - telegram_token
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - shared_network

secrets:
  telegram_token:
    environment: "TELEGRAM_BOT_TOKEN"

networks:
  shared_network:
    name: ember-main-${ENVIRONMENT}
    external: true
