services:
  telegram_bot:
    restart: always
    build: .
    environment:
      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_TOKEN_FILE: /run/secrets/telegram_token
      BROKESHIRE_API_URL: http://brokeshire-api-${ENVIRONMENT}/v1
      FF_BROKESHIRE_WALLET:
    secrets:
      - telegram_token
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - shared_network

secrets:
  telegram_token:
    environment: "TELEGRAM_BOT_TOKEN"

networks:
  shared_network:
    name: brokeshire-main-${ENVIRONMENT}
    external: true
