version: '3.9'

services:
  chroma_server:
    image: server
    build:
      context: ./chroma
      dockerfile: Dockerfile
    volumes:
      - ./chroma:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 10 --host 0.0.0.0 --port 8000 --log-config log_config.yml
  firepot_chatgpt_app:
    image: node:18.18-alpine
    command: sh -c "apk add --no-cache --virtual .gyp g++ make py3-pip && yarn global add node-gyp && yarn install && yarn run start"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - chroma_server
volumes:
  index_data:
    driver: local
