version: '3.9'

# networks:
#   net:
#     driver: bridge
services:
  chroma_server:
    image: ghcr.io/chroma-core/chroma:0.4.5
      #     volumes:
      #       - index_data:/chroma/.chroma/index
    ports:
      - "8000:8000"
  firepot_chatgpt_app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - chroma_server
volumes:
  index_data:
    driver: local
        #   backups:
        #     driver: local
