version: '3.9'

services:
  chroma_server:
    image: server
    build:
      context: ./chroma
      dockerfile: Dockerfile
    volumes:
      - ./chroma:/chroma
      - index_data:/index_data
  firepot_chatgpt_app:
    image: node:18.18-alpine
    #command: sh -c "apk add --no-cache --virtual .gyp g++ make py3-pip && yarn global add node-gyp && yarn install && yarn run start"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - chroma_server
    networks:
      - first_project_default
volumes:
  index_data:
    driver: local
networks:
  first_project_default:
    external: true
    name: ember-engine-stage_default