services:
  firepot_chatgpt_app:
    build: .
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - shared_network

  chroma_server:
    extends:
      file: docker-compose.yml
      service: chroma_server
    restart: always
    command: uvicorn chromadb.app:app --reload --workers 10 --host 0.0.0.0 --port 8001 --log-config log_config.yml
    networks:
      - shared_network

volumes:
  index_data:
    driver: local

networks:
  shared_network:
    external: true
