-- Create database and revoke public permission
CREATE DATABASE :DB_NAME;
REVOKE ALL ON DATABASE :DB_NAME FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- Creatr user role with connect permissions
CREATE USER :DB_USER WITH ENCRYPTED PASSWORD :DB_PASSWORD;
GRANT CONNECT ON DATABASE :DB_NAME TO :DB_USER;
GRANT TEMPORARY ON DATABASE :DB_NAME TO :DB_USER;