BEGIN TRANSACTION;

-- Remove public and create new schema
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS :DB_SCHEMA;

-- Grant usage on schema and sequences
GRANT USAGE, CREATE ON SCHEMA :DB_SCHEMA TO :DB_ADMIN_USER;
GRANT USAGE ON SCHEMA :DB_SCHEMA TO :DB_USER;
GRANT ALL ON ALL SEQUENCES IN SCHEMA :DB_SCHEMA TO :DB_ADMIN_USER;

-- Set search path
ALTER ROLE :DB_ADMIN_USER SET search_path TO :DB_SCHEMA;
ALTER ROLE :DB_USER SET search_path TO :DB_SCHEMA;

COMMIT;