BEGIN TRANSACTION;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA :DB_SCHEMA TO :DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA :DB_SCHEMA
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :DB_USER;

COMMIT;
