name: Server Deployment (Staging)

on: workflow_dispatch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up SSH environment
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_KEY }} >> ~/.ssh/known_hosts

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.21.0

      - name: Deploy containers in server
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          SECRET_SALT: ${{ secrets.SECRET_SALT }}
          TELEGRAM_BOT_USERNAME: ${{ vars.TELEGRAM_BOT_USERNAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
          IS_TESTNET: ${{ vars.IS_TESTNET }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FUNDING_WALLET_ID: ${{ secrets.FUNDING_WALLET_ID }}
          DB_PORT: ${{ vars.DB_PORT }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          FF_EMBER_WALLET: ${{ vars.FF_EMBER_WALLET }}
          ENVIRONMENT: staging
          SQUID_INTEGRATOR_ID: ${{ secrets.SQUID_INTEGRATOR_ID }}
        run: |
          docker compose -f compose.yaml -p ember-engine-$ENVIRONMENT up -d --build
