name: Server Deployment (Development)

on:
  push:
    branches: [main]
    paths:
      - package.json
      - pnpm-lock.yaml
      - src/**
      - db/**
      - tsconfig.*
      - .github/workflows/deploy-dev.yml
      - compose.yaml
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up SSH environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/known_hosts

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.21.0

      - name: Deploy containers in server
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          TELEGRAM_BOT_USERNAME: ${{ vars.TELEGRAM_BOT_USERNAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          FF_BROKESHIRE_WALLET: ${{ vars.FF_BROKESHIRE_WALLET }}
          ENVIRONMENT: development
        run: |
          docker compose -f compose.yaml -p telegram-bot-$ENVIRONMENT up -d --build --remove-orphans
