name: Server Deployment (Staging)

on:
  push:
    branches: [trunk]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "SECRET_SALT=${{ secrets.SECRET_SALT }}" >> .env
          echo "TELEGRAM_BOT_USERNAME=${{ vars.TELEGRAM_BOT_USERNAME }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "ARBITRUM_RPC_URL=${{ secrets.ARBITRUM_RPC_URL }}" >> .env
          echo "IS_TESTNET=${{ vars.IS_TESTNET }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "FUNDING_WALLET_ID=${{ secrets.FUNDING_WALLET_ID }}" >> .env
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_KEY }} >> ~/.ssh/known_hosts

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy containers in server
        uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: compose.yaml
          up-flags: -d --build
          compose-flags: -p ember-engine_stage
        env:
          DOCKER_HOST: "ssh://${{ secrets.SSH_USERNAME }}@${{ vars.SSH_HOST }}"
